language: perl
perl:
  - "5.18"
  - "5.20"
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
install:
  cpanm --quiet --installdeps --notest --with-recommends .
script:
- perl Build.PL && ./Build test
- RIJI_TEST_INTERNAL=1 ./Build build && cover -test -report coveralls
